### PR TITLE
Added empty $html variable

### PR DESCRIPTION
**Pull request by sameerkanda**
I'm using Jade with Laravel and it's going all crazy throwing an error! Plz fix.

### CODE REVIEW

**Comment by SebastienElet** [comment]
Thanks a lot, i miss this one.
Could you send me an example of this case to add the test and avoid regression ?

**Comment by sameerkanda** [comment]
Basically the error popped up anytime I ran a PHP code in Jade, example:

!!! 5
html(ng-app="loadtest")
    head
        body
            - foreach($array as $key => $val):

The "- foreach..." caused this error:

Undefined variable: $html in Dumper.php line 267: "$html .= '<?php ' . preg_replace('/^ +/', '', $node->code) . ' ?>';" ($html is not defined, so $html .= will screw up)

**Comment by sameerkanda** [comment]
tabs are not showing properly in my previous comment, but you get the idea

**Comment by SebastienElet** [comment]
Outch, i was focus on native jade test suite and i miss the main feature.
Thanks a lot for your feedback.

**Pull request merged**
